SIGNAL_CATEGORIES = ["emergency_help_request", "infrastructure_or_property_damage", "emotional_reaction_to_wildfire", "official_emergency_announcement"]
NOISE_CATEGORIES = ["non_emergency_daily_chatter", "wildfire_related_misinformation", "scam_or_unsolicited_promotions"]

TEMPLATES = {
    "emergency_help_request": [
        "{relation} is trapped {location}. We need {urgency_phrase}!",
        "Can someone help {relation} {location}? They're stuck and can't get out.",
        "We're surrounded by smoke {location}. Please {action_request}.",
        "{relation} is missing near {location}. Last seen during evacuation.",
        "The fire is closing in {location}. We need help {urgency_adverb}.",
        "{relation} is having trouble breathing from the smoke {location}. Please send {supply_request}.",
        "If anyone sees {relation}, they were last spotted {location}.",
        "Still no power or signal {location}. We can't reach {relation}.",
        "Trapped {location}, can't leave. Flames are blocking the road. {action_request}",
        "No way out from {location}. Fire is spreading fast. Need {urgency_phrase}.",
        "Trying to get elderly folks out {location}. We need assistance {urgency_adverb}.",
        "Stuck with small kids {location}. Too much smoke. Please {action_request}.",
        "Is anyone coordinating evac {location}? There are still people here.",
        "We've been calling for help all night {location}. Still no response.",
        "We're out of {supply_request} {location} and can't leave safely.",
        "{relation} went to help neighbors and hasn't come back. Last seen {location}.",
        "Roads are blocked {location}. Fire on both sides. Please help.",
        "{relation} can't walk and we're still {location}. Urgent support needed.",
        "Evacuation required {location}. Structure is catching fire.",
        "We can't breathe {location}. Visibility is zero. Need help {urgency_adverb}."
    ],
    "infrastructure_or_property_damage": [
        "Our {property_type} is {destruction_level}. We couldn't do anything.",
        "Photos show {damage_signs} all over {area_reference}.",
        "{fire_behavior} {damage_action} our {buildings} completely.",
        "This is {emotional_reaction}. Everything's gone.",
        "{severity_level} damage to {type_of_assets} reported in {macroarea_section}.",
        "Still no word on {infrastructure_type}. It's {current_state}.",
        "The {infrastructure_type} remains {current_state} in {vicinity_zone}.",
        "{direction_reference} was hit hard — {damage_summary}.",
        "Crews assessing damage to {infrastructure_type_plural}.",
        "The road into {local_area} is blocked — {damage_signs} everywhere.",
        "The fire reached our {property_type} and {type_of_assets} are gone.",
        "{region_type} suffered {severity_level} structural loss.",
        "We lost everything — {structure_type_plural}, {type_of_assets}, even {specific_item}."
    ],
    "emotional_reaction_to_wildfire": [
        "I've never seen anything like this.",
        "This is {emotional_intensity}… can't wrap my head around it.",
        "What's happening right now is beyond {emotional_limit}.",
        "Still trying to process what I just saw.",
        "Honestly, this feels {emotion_adjective}.",
        "The sky is {sky_description} and the air smells like {air_quality}.",
        "It's just {emotion_adjective} seeing this unfold.",
        "I can't stop thinking about how {scale_description} this is.",
        "Is this real life? Everything looks {visual_impact}.",
        "I stepped outside and the {surrounding_description} nearly made me cry.",
        "This whole thing is so {emotion_adjective}, I don't even know what to say.",
        "We're watching {scene_reference} in real time. This is wild.",
        "The air feels {air_feeling} and the sky is glowing {sky_color}.",
        "Everyone on this street looks {people_emotion}.",
        "It's hard to describe how {emotional_intensity} this feels in person.",
        "This looks like a scene from {movie_comparison}.",
        "I'm just {reaction_state}, trying to stay calm.",
        "My timeline is full of {content_type}. This is overwhelming.",
        "People {people_behavior} out here. You can feel the tension."
    ],
    "official_emergency_announcement": [
        "{agency} has issued a {directive_type} for {area_affected}.",
        "{evacuation_action} is in place for residents of {area_affected}.",
        "Authorities confirm {incident_update} as of this morning.",
        "{road_status} reported due to fire conditions.",
        "{agency} urges people to {public_instruction} immediately.",
        "Firefighters are battling {fire_behavior} near {location_reference}.",
        "Shelter is available at {shelter_location} for those affected.",
        "{agency} confirms damage to {public_asset} in {area_affected}.",
        "{utility_type} has been shut off in {area_affected} for safety.",
        "Emergency services are focusing efforts on {response_focus}.",
        "{area_affected} has been declared a {safety_status}.",
        "Evacuation centers include {shelter_location} and others nearby.",
        "Nearby roads are closed to all traffic due to {closure_reason}.",
        "Residents in {area_affected} should {public_instruction} until further notice.",
        "{agency} is coordinating with local units to address {response_focus}.",
        "Updates will be provided as they become available.",
        "Avoid {location_reference} — {hazard_warning} in the area."
    ],
    "non_emergency_daily_chatter": [
        "Not even gonna lie, I can't stop thinking about {trending_topic}.",
        "I was just remembering {nostalgic_topic}. Wild times.",
        "Why is everyone pretending {entertainment_item} wasn't amazing?",
        "I need a break. Maybe I'll dive into {entertainment_item}.",
        "Anyone else stuck in a loop of {random_thought}?",
        "This weather makes me want {food_craving} and a nap.",
        "Still thinking about that {trending_topic} from yesterday.",
        "Is it weird I'm rewatching {entertainment_item} for the third time?",
        "I miss the days of {nostalgic_topic}.",
        "Woke up with {random_thought} in my head.",
        "I'm craving {food_craving} and I'm not even hungry.",
        "Scrolling through my feed and it's all {trending_topic}.",
        "Currently avoiding everything by watching {entertainment_item}.",
        "That moment when {random_thought} hits you out of nowhere.",
        "Let's be honest, {personal_complaint} is the real problem."
        ],
    "wildfire_related_misinformation": [
        "People are saying the fires were started intentionally by {government} to clear land for {beneficiary}.",
        "I don't trust the official story — sounds like something {elites} {orchestration_term}.",
        "Why isn't {media_entity} talking about how {military_reference} were seen near the ignition zone?",
        "Someone told me this is all a test run by {elites} for {agenda}.",
        "The timing of the fires is too perfect. Makes you wonder if {beneficiary} are behind it.",
        "I saw a thread claiming this was {orchestration_term} to push the {agenda}.",
        "Apparently {satellite_term} were doctored to hide what's really happening.",
        "Word is that certain {protected_zone} were 'allowed' to burn while others were spared.",
        "They say {emergency_alert} are just a distraction for something bigger going on.",
        "Don't be fooled — this whole disaster feels too {orchestration_term} to be natural."
        ],
    "scam_or_unsolicited_promotions": [
        "Click here for instant updates on fire safety: {suspicious_link}",
        "Protect your home now with this {fake_product}! Limited stock!",
        "Claim your free wildfire compensation now at {spam_url} — act fast!",
        "Local fire relief fund accepting donations via {sketchy_payment_method} only.",
        "Special sale: Get 70% off on survival gear now! {promo_link}",
        "Don't wait! This {miracle_offer} could save your family during a fire.",
        "Earn easy money from home tracking fires — check {scam_site} for more info!",
        "Our {unverified_kit} is trusted by top responders. Get yours before it's too late.",
        "Urgent: You've been selected for a free {emergency_giveaway}. Confirm now!",
        "Disaster-proof your house with our premium {fake_product} — just released!",
        "You won't believe this offer: {miracle_offer} now 80% off at {promo_link}.",
        "Get your {unverified_kit} shipped today — pay using {sketchy_payment_method}.",
        "Support local relief by donating through {sketchy_payment_method}. It's fast and secure.",
        "Click {suspicious_link} for the only verified map you need.",
        "Receive a free {emergency_giveaway} — just cover shipping at {spam_url}."
        ]   
}

SYNONYMS = {

  "relation": [
        "my brother", "my grandma", "my dad", "my daughter", "a friend",
        "my neighbor", "my uncle", "my mom", "my partner", "my cousin"
    ],
    "location": [
        "near the park", "by the school", "close to the highway", "in our neighborhood", "near the grocery store", "just outside our house", "by the woods",
        "next to the main road", "at the shelter", "at the corner of our street", "behind the gas station", "near the local clinic",
        "in the field across from us", "close to the river", "on the edge of the evacuation zone", "behind the church", "in the alley behind the apartments",
        "on the hillside trail", "near the abandoned barn"
    ],
    "urgency_phrase": ["emergency assistance", "immediate help", "urgent support", "quick response", "rescue now"],
    "urgency_adverb": ["urgently", "immediately", "right away", "ASAP", "as soon as possible"],
    "action_request": ["send help", "call emergency services", "dispatch someone", "get a rescue team", "alert authorities"],
    "supply_request": ["water", "oxygen", "medical supplies", "inhalers", "a first aid kit"],


    "structure_type_plural": ["houses", "buildings", "structures", "homes", "residences", "cabins"],
    "damage_action": ["burned down", "consumed", "engulfed", "reduced to ash", "collapsed", "wiped out"],
    "property_type": ["property", "business", "workshop", "cabin", "home", "garage"],
    "destruction_level": ["lost", "obliterated", "completely ruined", "beyond saving", "unsalvageable"],
    "damage_signs": ["charred trees", "melted fences", "collapsed roofs", "scorched ground", "burnt debris"],
    "area_reference": ["this zone", "our block", "down the slope", "the neighborhood", "this stretch"],
    "fire_behavior": ["Extreme heat", "Firestorms", "Flying embers", "Wind-driven flames", "Flashover"],
    "buildings": ["structures", "homes", "residences", "units"],
    "emotional_reaction": ["heartbreaking", "devastating", "unreal", "sickening", "soul-crushing"],
    "severity_level": ["severe", "irreparable", "catastrophic", "massive", "widespread"],
    "type_of_assets": ["vehicles", "equipment", "tools", "generators", "trailers"],
    "macroarea_section": ["Sector A", "Zone 2", "Zone 5", "this area", "Block 9"],
    "infrastructure_type": ["power lines", "road access", "cell tower", "fiber lines", "utility pole"],
    "current_state": ["non-functional", "destroyed", "out of service", "damaged", "offline"],
    "region_type": ["the northern stretch", "the lower canyon", "the outskirts", "the valley edge", "the ridge"],
    "infrastructure_type_plural": ["roads and bridges", "communication lines", "utilities", "transport networks", "fiber networks"],
    "vicinity_zone": ["the area around us", "the outskirts", "the valley pass", "nearby sectors", "the lower area"],
    "local_area": ["this area", "our side", "the neighborhood", "the upper road", "this block"],
    "direction_reference": ["the west", "upwind", "the canyon rim", "the far side", "the hills"],
    "damage_summary": ["total loss reports", "extensive fire damage", "charred terrain", "infrastructure collapse", "fire devastation"],
    "specific_item": ["shed", "tools", "solar panels", "outdoor gear", "workbench"],


    "emotional_intensity": ["overwhelming", "shocking", "unreal", "surreal", "devastating"],
    "emotional_limit": ["words", "belief", "comprehension", "anything I imagined", "understanding"],
    "emotion_adjective": ["devastating", "unbelievable", "terrifying", "heartbreaking", "haunting"],
    "sky_description": ["orange", "glowing red", "completely gray", "covered in smoke", "dim and dusty"],
    "air_quality": ["ash", "smoke", "burnt wood", "chemicals", "dust"],
    "scale_description": ["massive", "beyond control", "unthinkable", "historic", "impossible to grasp"],
    "visual_impact": ["apocalyptic", "like a nightmare", "out of a movie", "unreal", "ghostly"],
    "surrounding_description": ["thick smoke", "burnt trees", "flashing lights", "sirens", "chaos"],
    "scene_reference": ["entire hillside on fire", "black clouds rising", "flames creeping down", "evacuations", "neighborhood burning"],
    "air_feeling": ["heavy", "thick", "toxic", "suffocating", "hot and dry"],
    "sky_color": ["orange", "blood red", "grayish", "eerie yellow", "pink"],
    "people_emotion": ["stunned", "worried", "in shock", "silent", "panicked"],
    "sun_appearance": ["barely visible", "red and low", "blurred out", "a glowing dot", "surrounded by haze"],
    "movie_comparison": ["a disaster movie", "a war zone", "something post-apocalyptic", "a sci-fi film", "an action scene"],
    "reaction_state": ["numb", "exhausted", "anxious", "stunned", "overwhelmed"],
    "content_type": ["videos of flames", "photos of smoke", "evacuation alerts", "scenes of panic", "maps and warnings"],
    "people_behavior": ["standing around", "filming everything", "trying to stay calm", "crying", "leaving quickly"],


    "agency": ["Cal Fire", "Emergency Services", "Fire Department", "Local Officials", "Incident Command"],
    "directive_type": ["mandatory evacuation", "evacuation warning", "shelter-in-place order", "fire advisory", "hazard alert"],
    "area_affected": ["the affected region", "Zone 3", "Sector D", "the lower canyon", "this district"],
    "evacuation_action": ["mandatory evacuation", "voluntary evacuation", "shelter-in-place order", "emergency relocation"],
    "incident_update": ["structural damage", "full evacuation", "loss of power", "confirmed injuries", "containment progress"],
    "road_status": ["closure", "limited access", "obstructions", "ongoing monitoring", "lane restrictions"],
    "public_instruction": ["evacuate", "avoid the area", "limit travel", "stay alert", "follow official guidance"],
    "fire_behavior": ["intense flames", "rapid spread", "spot fires", "strong winds", "flare-ups"],
    "location_reference": ["the west ridge", "the southern perimeter", "north of the canyon", "near Zone B", "the outskirts"],
    "shelter_location": ["Hillview Center", "Central High Gym", "North Creek Shelter", "Zone A Relief Point", "Local Evac Site"],
    "public_asset": ["transmission lines", "community center", "local clinic", "school grounds", "fire lookout"],
    "utility_type": ["electricity", "gas", "water", "internet services", "power grid"],
    "response_focus": ["protecting structures", "supporting evacuations", "restoring utilities", "ensuring safety", "slowing spread"],
    "safety_status": ["disaster zone", "restricted area", "state of emergency", "high-risk zone", "hazard zone"],
    "closure_reason": ["fire activity", "downed trees", "smoke conditions", "firefighting operations", "public safety"],
    "hazard_warning": ["active flames", "low visibility", "falling debris", "heat risks", "unpredictable winds"],

    "trending_topic": ["the game", "that episode", "the new album", "a dumb meme", "a weird post"],
    "nostalgic_topic": ["old cartoons", "summer break", "those school trips", "my childhood room", "the music back then"],
    "entertainment_item": ["that series", "the documentary", "a rom-com", "a comfort show", "some random video"],
    "random_thought": ["cloud shapes", "old dreams", "unfinished to-do lists", "a weird noise", "nothing at all"],
    "food_craving": ["noodles", "french fries", "cheesecake", "ice cream", "pancakes"],
    "personal_complaint": ["this headache", "bad Wi-Fi", "slow loading screens", "group chats", "the algorithm"],

    "government": ["the government", "federal agencies", "authorities", "official institutions", "state powers"],
    "beneficiary": ["real estate developers", "tech corporations", "private investors", "big business", "elite contractors"],
    "elites": ["the elites", "powerful figures", "those in charge", "the ruling class", "high-level officials"],
    "orchestration_term": ["planned", "engineered", "coordinated", "set up", "orchestrated"],
    "media_entity": ["the media", "mainstream news", "corporate media", "news outlets", "press"],
    "military_reference": ["the military", "army units", "special forces", "military personnel", "defense contractors"],
    "agenda": ["a control agenda", "land seizures", "population management", "surveillance expansion", "urban restructuring"],
    "satellite_term": ["satellite images", "drone footage", "surveillance data", "imagery records", "aerial visuals"],
    "protected_zone": ["communities", "districts", "wealthy areas", "zones", "neighborhoods"],
    "emergency_alert": ["emergency alerts", "warning systems", "public notifications", "official messages", "crisis broadcasts"],

    "suspicious_link": ["fire-safe-info.now", "emergency-updates.link", "alerts247.live"],
    "fake_product": ["fireproof blanket", "emergency spray", "evacuation kit"],
    "spam_url": ["claim-help.net", "govsupport.click", "relief-cash.org"],
    "sketchy_payment_method": ["Venmo", "gift cards", "PayPal friends"],
    "promo_link": ["firesale.today", "gearupfast.io", "disasterdeals.biz"],
    "miracle_offer": ["magic patch", "instant shield", "fireproof wrap"],
    "scam_site": ["earn-from-alerts.biz", "fireincome.stream", "smokejobs.co"],
    "unverified_kit": ["survival box", "emergency pack", "defense shield"],
    "emergency_giveaway": ["evac kit", "smoke alarm", "fire alert device"]
}