SIGNAL_CATEGORIES = ["emergency_help_request", "infrastructure_or_property_damage", "emotional_reaction_to_wildfire", "official_emergency_announcement"]
NOISE_CATEGORIES = ["non_emergency_daily_chatter", "wildfire_related_misinformation", "scam_or_unsolicited_promotions"]

TEMPLATES = {
    "emergency_help_request": [
    "We're {urgency_term} in need of help — {people_count} people here, can't get out.",
    "Trapped near {landmark_reference}. Anyone with {transport_means} available?",
    "Can someone send {aid_type}? We're stuck and the fire is getting {fire_progress}.",
    "We have {family_members} and no way to leave. Please, {help_plea}.",
    "Need {emergency_item} urgently. {vulnerable_persons} can't move alone.",
    "Our road is blocked near {direction}. Fire is {fire_behavior}. We need help now.",
    "SOS: {problem_description} — send help to coordinates ASAP!",
    "We can see flames approaching from {direction}, and we're {emergency_status}.",
    "Requesting evacuation support for {location_description}. Fire is {fire_threat_level}.",
    "We're out of {supply_item} and stuck in {shelter_condition}. Please help."
    ],
    "infrastructure_or_property_damage": [
        "Multiple {structure_type_plural} were {damage_action} just past {landmark_reference}.",
        "Our {property_type} was {destruction_level} after the flames reached {nearby_location}.",
        "Flames have {damage_action} everything around {local_area}, including {infrastructure_type}.",
        "Massive damage reported in {microarea_name} — {number_affected} {buildings} affected.",
        "Seeing {damage_signs} around {area_reference}, it's {emotional_reaction}.",
        "{fire_behavior} caused {severity_level} damage to {type_of_assets} near {region_type}.",
        "We lost {specific_item} to the wildfire — it reached us from {direction_reference}.",
        "Emergency services reported {damage_summary} across {macroarea_section}.",
        "{infrastructure_type_plural} in {vicinity_zone} are {current_state} due to the fire."
    ],
    "emotional_reaction_to_wildfire": [
        "This fire is {emotion_word}... I've never seen anything like this in {time_frame}.",
        "I'm really {feeling_state} about what's happening out there near {direction}.",
        "It's {adjective} to see the smoke getting closer every hour — it's {visibility_condition} now.",
        "I'm {emotional_response} — can't stop thinking about it since {event_trigger}.",
        "Feeling {worried_term} with all these fires around and {air_quality} air.",
        "Everything smells like smoke, and I'm getting really {nervous_state}, especially at {time_of_day}.",
        "I don't feel {safe_word} anymore with the fire so close to {proximity_reference}.",
        "The air is thick, and the sky is orange. I'm honestly {emotion_word} and {reaction_phrase}.",
        "People are leaving… it's all starting to feel very {intense_feeling}, especially with {news_source} updates.",
        "Never thought I'd be this {fear_level} of a wildfire — the {fire_behavior} makes it worse."
    ],
    "official_emergency_announcement": [
        "{alert_type}: Wildfire {fire_status} in the area. {instruction} {urgency}.",
        "{agency} has issued an {alert_level} alert due to {fire_behavior}. {evacuation_advice}.",
        "Wildfire {intensity} reported nearby. {authority} urges residents to {evacuation_action} {urgency}.",
        "{evacuation_instruction} now in effect. {reason}. Stay {safe_word}.",
        "‼{region_type} is under {alert_type}. {response_advice}.",
        "Due to {fire_conditions}, {emergency_service} advises everyone to {evacuation_step} immediately.",
        "Emergency: {fire_description}. {residents_instruction}.",
        "{organization} reports {wildfire_status} in this area. {action_needed} for your safety.",
        "{fire_agency} warns about {situation_description}. Follow all {guidance_type}.",
        "{evacuation_zone} is now under mandatory evacuation. {evacuation_reason}."
    ],
    "non_emergency_daily_chatter": [
        "Just got back from the grocery store — they finally had my favorite {snack_item}!",
        "Anyone else obsessed with the {tv_show} finale last night?",
        "The {sports_team} game was intense — didn't expect that ending!",
        "Took a stroll through {local_place} this morning. So peaceful.",
        "Been trying out new recipes — today's dish: {food_experiment}!",
        "Working from home has me redecorating my {room_in_house}.",
        "Started a new book: {book_title}. Highly recommend it so far!",
        "Anyone in {neighborhood_name} know a good place for {service_needed}?",
        "My {pet_type} has been acting so goofy today. Must be the weekend vibes."
        ],
    "wildfire_related_misinformation": [
        "People are saying the fires were started intentionally by {government} to clear land for {beneficiary}.",
        "I don't trust the official story — sounds like something {elites} {orchestration_term}.",
        "Why isn't {media_entity} talking about how {military_reference} was seen near the ignition zone?",
        "Someone told me this is all a test run by {elites} for {agenda}.",
        "The timing of the fires is too perfect. Makes you wonder who {beneficiary}.",
        "I saw a thread claiming this was {orchestration_term} to push the {agenda}.",
        "Apparently {satellite_term} were doctored to hide what's really happening.",
        "Word is that certain {protected_zone} were 'allowed' to burn while others were spared.",
        "They say {emergency_alert} are just a distraction for something bigger going on.",
        "Don't be fooled — this whole disaster feels too {orchestration_term} to be natural."
        ],
    "scam_or_unsolicited_promotions": [
        "Click here for instant updates on fire safety: {suspicious_link}",
        "Protect your home now with this {fake_product}! Limited stock!",
        "Claim your free wildfire compensation now at {spam_url} — act fast!",
        "Local fire relief fund accepting donations via {sketchy_payment_method} only.",
        "Special sale: Get 70% off on survival gear now! {promo_link}",
        "Don't wait! {miracle_offer} could save your family during a fire.",
        "Earn easy money from home tracking fires — check {scam_site} for more info!",
        "Our {unverified_kit} is trusted by top responders. Get yours before it's too late.",
        "Urgent: You've been selected for a free {emergency_giveaway}. Confirm now!"
]
}

SYNONYMS = {

  "urgency_term": ["desperately", "urgently", "badly"],
  "people_count": ["four", "six", "a few"],
  "landmark_reference": ["a dry riverbed", "a small hill", "a radio tower"],
  "transport_means": ["a vehicle", "an off-road car", "a rescue truck"],
  "aid_type": ["help", "evacuation", "rescue support"],
  "fire_progress": ["closer", "worse", "out of control"],
  "family_members": ["kids and grandparents", "my parents", "a baby and elderly"],
  "help_plea": ["please help us", "send help now", "we need rescue"],
  "emergency_item": ["water", "medical supplies", "a stretcher"],
  "vulnerable_persons": ["my grandmother", "my injured brother", "an elderly couple"],
  "direction": ["north", "uphill", "by the trees"],
  "fire_behavior": ["closing in", "burning fast", "spreading rapidly"],
  "problem_description": ["roof caught fire", "we're surrounded by smoke", "can't see anything"],
  "emergency_status": ["trapped", "panicking", "cut off"],
  "location_description": ["a tent site", "a parking lot", "an open field"],
  "fire_threat_level": ["a serious threat", "getting worse", "visible from here"],
  "supply_item": ["food", "clean water", "phone battery"],
  "shelter_condition": ["a car", "a broken shelter", "the woods"],

  "structure_type_plural": ["houses", "buildings", "structures"],
  "damage_action": ["burned down", "consumed", "engulfed"],
  "property_type": ["property", "business", "cabin"],
  "destruction_level": ["lost", "obliterated", "completely ruined"],
  "nearby_location": ["the ridge", "the lower road", "the hilltop"],
  "local_area": ["this area", "our side", "the neighborhood"],
  "infrastructure_type": ["power lines", "road access", "cell tower"],
  "microarea_name": ["Zone 1", "Zone 2", "Zone 5", "Sector A"],
  "number_affected": ["dozens of", "many", "several"],
  "buildings": ["structures", "homes", "residences"],
  "damage_signs": ["charred trees", "melted fences", "collapsed roofs"],
  "area_reference": ["this zone", "our block", "down the slope"],
  "emotional_reaction": ["heartbreaking", "devastating", "unreal"],
  "fire_behavior": ["Extreme heat", "Firestorms", "Flying embers"],
  "severity_level": ["severe", "irreparable", "catastrophic"],
  "type_of_assets": ["vehicles", "equipment", "livestock pens"],
  "region_type": ["the northern stretch", "the lower canyon", "the outskirts"],
  "specific_item": ["shed", "tools", "solar panels"],
  "direction_reference": ["the west", "upwind", "the canyon rim"],
  "damage_summary": ["total loss reports", "extensive fire damage", "charred terrain"],
  "macroarea_section": ["Sector A", "Zone 2", "this region"],
  "infrastructure_type_plural": ["roads and bridges", "communication lines", "utilities"],
  "vicinity_zone": ["the area around us", "the outskirts", "the valley pass"],
  "current_state": ["non-functional", "destroyed", "out of service"],

    "emotion_word": ["terrifying", "overwhelming", "unreal"],
  "time_frame": ["recent days", "this week", "today"],
  "feeling_state": ["anxious", "worried", "uneasy"],
  "direction": ["the north", "the hills", "down south"],
  "adjective": ["horrifying", "frightening", "intense"],
  "visibility_condition": ["barely visible", "completely dark", "thick with smoke"],
  "emotional_response": ["on edge", "distraught", "shaken"],
  "event_trigger": ["the alert", "the first flames", "this morning"],
  "worried_term": ["tense", "concerned", "nervous"],
  "air_quality": ["toxic", "thick", "unbreathable"],
  "nervous_state": ["restless", "jumpy", "spooked"],
  "time_of_day": ["nightfall", "sunset", "early morning"],
  "safe_word": ["safe", "secure", "protected"],
  "proximity_reference": ["the ridge", "our zone", "the valley"],
  "reaction_phrase": ["losing sleep", "ready to flee", "frozen in fear"],
  "intense_feeling": ["too real", "out of control", "like a nightmare"],
  "news_source": ["emergency app", "live updates", "radio alert"],
  "fear_level": ["scared", "terrified", "freaked out"],
  "fire_behavior": ["flames spreading fast", "unpredictable winds", "roaring smoke"],

  "alert_type": ["Evacuation Warning", "Fire Alert", "Critical Emergency"],
  "fire_status": ["spreading rapidly", "burning out of control"],
  "instruction": ["Evacuate immediately", "Prepare to leave", "Follow emergency protocols"],
  "urgency": ["Do not delay", "Time is critical", "This is not a drill"],
  "agency": ["Cal Fire", "FEMA", "Local Authorities"],
  "alert_level": ["red", "maximum", "high-priority"],
  "fire_behavior": ["unpredictable fire spread", "rapid ignition zones"],
  "evacuation_advice": ["Leave the area calmly", "Use main roads only"],
  "intensity": ["at level 4", "growing fast"],
  "authority": ["Emergency Management", "Wildfire Response Unit"],
  "evacuation_action": ["evacuate", "leave immediately"],
  "evacuation_instruction": ["Mandatory evacuation", "Evacuation order"],
  "reason": ["due to worsening fire conditions", "because of nearby flames"],
  "safe_word": ["safe", "alert", "aware"],
  "region_type": ["the affected region", "local zone"],
  "response_advice": ["Head to the nearest shelter", "Stay informed"],
  "fire_conditions": ["severe fire risk", "hot and windy weather"],
  "emergency_service": ["firefighters", "local responders"],
  "evacuation_step": ["evacuate", "stay indoors"],
  "fire_description": ["massive wildfire approaching", "smoke and flames visible"],
  "residents_instruction": ["Residents must leave now", "Avoid staying indoors"],
  "organization": ["California Emergency Alert System", "FireWatch"],
  "wildfire_status": ["spreading aggressively", "out of control"],
  "action_needed": ["Evacuate now", "Remain alert"],
  "fire_agency": ["Forest Service", "Emergency Command Center"],
  "situation_description": ["dangerous heat conditions", "multiple fire fronts"],
  "guidance_type": ["evacuation routes", "emergency orders"],
  "evacuation_zone": ["Zone 3", "This area"],
  "evacuation_reason": ["due to increased fire activity", "for your safety"],

  "snack_item": ["chips", "mochi ice cream", "energy bars"],
  "tv_show": ["Succession", "The Bear", "Bridgerton", "The Last of Us", "Ted Lasso"],
  "sports_team": ["Lakers", "49ers", "Giants", "Dodgers", "Warriors"],
  "local_place": ["the park", "Main Street", "our trail", "the farmers' market", "the library"],
  "food_experiment": ["zucchini noodles", "spicy tofu stir-fry", "coconut curry", "stuffed peppers", "banana pancakes"],
  "room_in_house": ["home office", "living room", "kitchen corner", "reading nook", "bedroom wall"],
  "book_title": ["Project Hail Mary", "Fourth Wing", "Atomic Habits"],
  "neighborhood_name": ["Greenwood", "Old Town", "Maple Ridge", "Cedar Heights", "Downtown East"],
  "service_needed": ["bike repair", "dog groomer", "plant nursery", "coffee spot", "dentist"],
  "pet_type": ["dog", "cat", "parrot", "goldfish"],

  "government": ["the government", "federal agencies", "authorities", "official institutions", "state powers"],
  "beneficiary": ["real estate developers", "tech corporations", "private investors", "big business", "elite contractors"],
  "elites": ["the elites", "powerful figures", "those in charge", "the ruling class", "high-level officials"],
  "orchestration_term": ["planned", "engineered", "coordinated", "set up", "orchestrated"],
  "media_entity": ["the media", "mainstream news", "corporate media", "news outlets", "press"],
  "military_reference": ["the military", "army units", "special forces", "military personnel", "defense contractors"],
  "agenda": ["a control agenda", "land seizures", "population management", "surveillance expansion", "urban restructuring"],
  "satellite_term": ["satellite images", "drone footage", "surveillance data", "imagery records", "aerial visuals"],
  "protected_zone": ["communities", "districts", "wealthy areas", "zones", "neighborhoods"],
  "emergency_alert": ["emergency alerts", "warning systems", "public notifications", "official messages", "crisis broadcasts"],

  "suspicious_link": ["fire-safe-info.now", "emergency-updates.link", "alerts247.live"],
  "fake_product": ["fireproof blanket", "emergency spray", "evacuation kit"],
  "spam_url": ["claim-help.net", "govsupport.click", "relief-cash.org"],
  "sketchy_payment_method": ["Venmo", "gift cards", "PayPal friends"],
  "promo_link": ["firesale.today", "gearupfast.io", "disasterdeals.biz"],
  "miracle_offer": ["magic patch", "instant shield", "fireproof wrap"],
  "scam_site": ["earn-from-alerts.biz", "fireincome.stream", "smokejobs.co"],
  "unverified_kit": ["survival box", "emergency pack", "defense shield"],
  "emergency_giveaway": ["evac kit", "smoke alarm", "fire alert device"]
}